name: Try build

on:
  push:
    branches: ["main"]
    tags-ignore:
      - "pwa@*"
      - "android@*"
      - "ios@*"
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
  schedule:
    - cron: "15 10 * * 5"

jobs:
  android:
    name: Build for PWA
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node_version: [16, 18, 20]
        include:
          # Active LTS + other OS
          - os: macos-latest
            node_version: 18
          - os: windows-latest
            node_version: 18
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.3.1
          run_install: false

      - name: Install depends
        run: sh install.sh

      - name: Build PWA
        run: pnpm build:pwa
  pwa:
    name: Build for Android
    runs-on: [ubuntu-latest, macos-latest]
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "17"

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.3.1
          run_install: false

      - name: Install depends
        run: sh install.sh

      - name: Build Quasar
        run: pnpm build:android:ci

      - name: Build Android App
        uses: anime-vsub/android-build-action@1.2.1
        with:
          project-path: src-capacitor/android
          output-path: apk-release.apk
          gradle-task: assembleRelease
